### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by karajan-37458** [karajan-37458/ChatSpace#9]
# IPアドレス
176.34.16.226

**Comment by mutorisa** [comment]
ご提出ありがとうございます！！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正箇所]**
○テキストの見本を参考にぢ、メッセージごとに間隔をとりましょう。

<img width="1043" alt="メッセージの間隔" src="https://user-images.githubusercontent.com/65144927/84874427-88e25d80-b0bf-11ea-8868-d96d74f4335b.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by karajan-37458** [comment]
修正のご指摘の意味が理解できかねます。
もう一度、具体的にご指示を願います。

**Comment by miyu-yamamoto** [comment]
柄澤さん、説明不足な部分があり大変失礼しました。

こちらは柄澤さんが作成してくださった実際のChatSpaceの画面なのですが
投稿されたメッセージとメッセージの間に感覚がなく、仕様書通りに作成できていない状況です。

**○ テキストの見本を参考にして、メッセージごとに間隔をとりましょう**
<img width="704" alt="スクリーンショット 2020-06-17 17 39 31" src="https://user-images.githubusercontent.com/59544869/84876046-bb8d5580-b0c1-11ea-8795-318b9fc32e22.png">

また追加で修正が必要となる箇所があります。
**○ グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう**
　一度リロードすることで2回以降は自動更新できています
<img width="450" alt="スクリーンショット 2020-06-16 10 12 07" src="https://user-images.githubusercontent.com/59544869/84876399-2474cd80-b0c2-11ea-8e66-522e9d33e07d.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by karajan-37458** [comment]
修正しました！

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！
